version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: geodb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: josue
      POSTGRES_DB: geo_pruebas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: geoespacial_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000

volumes:
  pgdata:
